Rails:
  Enabled: true

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'Rakefile'
    - 'Gemfile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'

Style/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  CountComments: false
  Max: 20

